name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  stages:
  - build
  - test
  - deploy
  - .post

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Deployment

    notification-job:
    stage: .post
    script:
      - echo "CI/CD pipeline"
      - >
        curl -X POST https://api.telegram.org/bot7442834678:AAHbjXuZQUmJO9Aj6kZ7aOAaNG-ehRFqLbk/sendMessage
        -d chat_id=628390613
        -d text="Deployment completed successfully!"

      
